debug: true

spring:
  aop:
    proxy-target-class: true


security:
  sessions: stateless
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9090/uaa/oauth/token
      userAuthorizationUri: http://localhost:9090/uaa/oauth/authorize
      clientId: myauthserver
      clientSecret: verysecretpassword
    resource:
      jwt:
        key-value: changeMEforPROD
        #keyValue: |
        #  -----BEGIN PUBLIC KEY-----
        #  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
        #  -----END PUBLIC KEY-----


zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
      sensitiveHeaders: Cookie, Set-Cookie
    admin:
      path: /admin/**
      url: http://localhost:9100/admin
      sensitiveHeaders:
    user:
      path: /user/**
      url: http://localhost:9090/uaa/user

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      resource: oauth2
      user: oauth2

logging:
  level:
    org.springframework.security: DEBUG